version: "3.9"

services:
  stocks1:
    build:
      context: ./stock-portfolio
    container_name: stocks1
    ports:
      - "5001:5001"
    environment:
      - NINJA_API_KEY=vopFoYntOSunu9wOgno8UQ==6N9s5bNi9ndGWM5I
      - MONGO_URI=mongodb://mongodb:27017/
      - SERVICE_NAME=stocks1_db
    restart: always

  stocks1_2:
    build:
      context: ./stock-portfolio
    container_name: stocks1_2
    ports:
      - "5004:5001"
    environment:
      - NINJA_API_KEY=vopFoYntOSunu9wOgno8UQ==6N9s5bNi9ndGWM5I
      - MONGO_URI=mongodb://mongodb:27017/
      - SERVICE_NAME=stocks1_db
    restart: always

  stocks2:
    build:
      context: ./stock-portfolio
    container_name: stocks2
    ports:
      - "5002:5001"
    environment:
      - NINJA_API_KEY=vopFoYntOSunu9wOgno8UQ==6N9s5bNi9ndGWM5I
      - MONGO_URI=mongodb://mongodb:27017/
      - SERVICE_NAME=stocks2_db
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  capital-gains:
    build:
      context: ./capital-gains
    container_name: capital-gains
    ports:
      - "5003:5003"
    environment:
      - STOCKS1_URL=http://stocks1:5001
      - STOCKS2_URL=http://stocks2:5002
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - stocks1
      - stocks1_2
      - stocks2
      - capital-gains    

volumes:
  mongo_data: